# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 690)
        self.bgwidget = QtWidgets.QWidget(Form)
        self.bgwidget.setGeometry(QtCore.QRect(0, -1, 561, 671))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(209, 107, 165, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 251, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 361, 41))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.loginbutton = QtWidgets.QPushButton(self.bgwidget)
        self.loginbutton.setGeometry(QtCore.QRect(100, 470, 341, 51))
        self.loginbutton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.loginbutton.setObjectName("loginbutton")
        self.email = QtWidgets.QLineEdit(self.bgwidget)
        self.email.setGeometry(QtCore.QRect(100, 300, 341, 51))
        self.email.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.email.setObjectName("email")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 270, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(440, 456, 341, 20))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.Password = QtWidgets.QLineEdit(self.bgwidget)
        self.Password.setGeometry(QtCore.QRect(100, 390, 341, 51))
        self.Password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Password.setObjectName("Password")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 360, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.loginbutton_2 = QtWidgets.QPushButton(self.bgwidget)
        self.loginbutton_2.setGeometry(QtCore.QRect(100, 540, 341, 51))
        self.loginbutton_2.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.loginbutton_2.setObjectName("loginbutton_2")
        self.loginbutton_3 = QtWidgets.QPushButton(self.bgwidget)
        self.loginbutton_3.setGeometry(QtCore.QRect(100, 600, 341, 51))
        self.loginbutton_3.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.loginbutton_3.setObjectName("loginbutton_3")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 170, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.email_2 = QtWidgets.QLineEdit(self.bgwidget)
        self.email_2.setGeometry(QtCore.QRect(100, 200, 341, 51))
        self.email_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.email_2.setPlaceholderText("")
        self.email_2.setObjectName("email_2")
        self.loginbutton.clicked.connect(self.insert_data)
        self.loginbutton_2.clicked.connect(self.delete) 
        self.loginbutton_3.clicked.connect(self.update)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def insert_data(self):

        try:


                db=mc.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database="login"    
                )
                mycursor=db.cursor()   
                email=self.email.text()
                Password=self.Password.text()

                query="INSERT INTO login_db (email,Password) VALUES (%s,%s)"
                value=(email,Password)
                mycursor.execute(query,value)
                db.commit()
                # self.label_4.setText("Data inserted")       
        except mc.Error as e:
                print("Error")
                # self.label_4.setText("Error")   
                #     
    def delete(self):
        try:

                db=mc.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database="login"    
                )
                mycursor=db.cursor()   
                email=self.email.text()
                
                deleteq= "DELETE FROM login_db WHERE email=%s"
                value=(email,)
                mycursor.execute(deleteq,value)
                db.commit() 
        except:
                print("Failed")

    def update(self):
        try:
                db=mc.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database="login"    
                )
                mycursor=db.cursor()   
                email=self.email.text()
                id=self.email_2.text()
                updateq= "UPDATE login_db SET id= %s,email=%s WHERE id=%s"
                value=(email,id)
                mycursor.execute(updateq,value)
                db.commit() 
        except:
                print("Failed")   
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Login page"))
        self.label_2.setText(_translate("Form", "Sign in to your existing account"))
        self.loginbutton.setText(_translate("Form", "Login"))
        self.label_3.setText(_translate("Form", "Email Id"))
        self.label_4.setText(_translate("Form", "Password"))
        self.loginbutton_2.setText(_translate("Form", "Delete"))
        self.loginbutton_3.setText(_translate("Form", "Update"))
        self.label_5.setText(_translate("Form", " Id"))

if __name__ == "__main__":
        import sys
        app=QtWidgets.QApplication(sys.argv)
        Form=QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())