# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel
from PyQt5.QtCore import QRegExp, QRegularExpression
import mysql.connector as mc
from PyQt5.QtWidgets import QWidget,QVBoxLayout,QLineEdit,QPushButton,QDialog,QMessageBox
from PyQt5.QtGui import QValidator,QRegExpValidator
class SecondWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('second window')
        self.setFixedWidth(500)
        self.setFixedHeight(400)
        self.label = QLabel('Welcome', self)
        
        
        mainLayout = QVBoxLayout()

        self.input1 = QLineEdit()
        self.input2 = QLineEdit()
        mainLayout.addWidget(self.input1)
        mainLayout.addWidget(self.input2)
        self.updatebutton= QPushButton('Update')
        self.updatebutton.clicked.connect(self.Update)
        mainLayout.addWidget(self.updatebutton)
        self.deletebutton= QPushButton('Delete')
        self.deletebutton.clicked.connect(self.delete)
        mainLayout.addWidget(self.deletebutton)
        self.closeButton = QPushButton('Close')
        self.closeButton.clicked.connect(self.close)
        mainLayout.addWidget(self.closeButton)
        
        self.setLayout(mainLayout)

    def Update(self):

        try:
                db=mc.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database="login"    
                )
                mycursor=db.cursor()   
                email=self.input1.text()
                Password=self.input2.text()
                updateq= "UPDATE login_db SET email=%s WHERE Password=%s"
                value=(email,Password)
                mycursor.execute(updateq,value)
                db.commit() 
        except:
                print("Failed")      
    def delete(self):
        try:

                db=mc.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database="login"    
                )
                mycursor=db.cursor()   
                email=self.input1.text()
                
                deleteq= "DELETE FROM login_db WHERE email=%s"
                value=(email,)
                mycursor.execute(deleteq,value)
                db.commit() 
        except:
                print("Failed")

              
    def displayInfo(self):
        self.show()

class Ui_Form13(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 560)
        self.bgwidget = QtWidgets.QWidget(Form)
        self.bgwidget.setGeometry(QtCore.QRect(0, -40, 561, 671))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(209, 107, 165, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 251, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 361, 41))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.loginbutton = QtWidgets.QPushButton(self.bgwidget)
        self.loginbutton.setGeometry(QtCore.QRect(100, 390, 341, 51))
        self.loginbutton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.loginbutton.setObjectName("loginbutton")
        self.email = QtWidgets.QLineEdit(self.bgwidget)
        self.email.setGeometry(QtCore.QRect(100, 200, 341, 51))
        self.email.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.email.setObjectName("email")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 170, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(440, 456, 341, 20))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.Password = QtWidgets.QLineEdit(self.bgwidget)
        self.Password.setGeometry(QtCore.QRect(100, 300, 341, 51))
        self.Password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Password.setObjectName("Password")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 270, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.loginbutton_2 = QtWidgets.QPushButton(self.bgwidget)
        self.loginbutton_2.setGeometry(QtCore.QRect(110, 490, 341, 51))
        self.loginbutton_2.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.loginbutton_2.setObjectName("loginbutton_2")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 460, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_5.setObjectName("label_5")
        self.loginbutton.clicked.connect(self.insert_data)
        self.loginbutton.clicked.connect(self.passingInformation)
        self.loginbutton_2.clicked.connect(self.opensignup)
        self.secondWindow = SecondWindow() 
        self.loginbutton.clicked.connect(Form.close)
        self.loginbutton_2.clicked.connect(Form.close)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        reg_e = QRegExp("[a-z 0-9]+[\._]?[a-z 0-9]+[@]\w+[.]\w{2,3}$")
        i = QRegExpValidator(reg_e, self.email)
        self.email.setValidator(i) 
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
    def opensignup(self):
        from register import Ui_Form1
        self.regwindow=QtWidgets.QMainWindow()
        self.ui=Ui_Form1()
        self.ui.setupUi(self.regwindow)
        self.regwindow.show()
  
    def insert_data(self):
    

        db=mc.connect(
                host="localhost",
                user="root",
                password="",
                database="login"    
        )
        mycursor=db.cursor()   
        email=self.email.text()
        Password=self.Password.text()

        query="SELECT * FROM login_db WHERE email=%s AND Password=%s"
        value=(email,Password)
        mycursor.execute(query,value)
        saharsh= mycursor.fetchall()
        
        if (len(email) and len(Password) )==0:

                self.email.setPlaceholderText('Please enter Email Id')
                self.Password.setPlaceholderText('Please enter Password')
        elif len(email)==0:
                self.email.setPlaceholderText('Please enter email id')

        elif len(Password)==0:
                self.Password.setPlaceholderText('Please enter Password')   
        else:
                      
                Form.close()                     
        if (len(saharsh))>0:
                print("user found")
        
                
        else:
                print("user not found")
                message_box=QMessageBox()
                message_box.warning(None,"Error","Input invalid") 
                # print("user not found")
        
                              
    def passingInformation(self):
        self.secondWindow.input1.setText(self.email.text())
        self.secondWindow.input2.setText(self.Password.text())
        self.secondWindow.displayInfo()
 
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Login page"))
        self.label_2.setText(_translate("Form", "Sign in to your existing account"))
        self.loginbutton.setText(_translate("Form", "Login"))
        self.label_3.setText(_translate("Form", "Email Id"))
        self.label_4.setText(_translate("Form", "Password"))
        self.loginbutton_2.setText(_translate("Form", "Signup"))
        self.label_5.setText(_translate("Form", "Don\'t have account. Register here"))

       
if __name__ == "__main__":
        import sys
        app=QtWidgets.QApplication(sys.argv)
        Form=QtWidgets.QMainWindow()
        ui = Ui_Form13()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())  
   